development:
  adapter: postgresql
  encoding: utf8
  database: simple_task_manager_development
  username: postgres
  password: 
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: simple_task_manager_test
  username: postgres
  password: 
  host: localhost